# Documentation: http://docs.travis-ci.com/user/languages/julia/
coveralls: true
codecov: true
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.2
  - 1.4
  - nightly

matrix:
  allow_failures:
  - julia: nightly


matrix:
  allow_failures:
  - julia: nightly


notifications:
    email:
      recipients:
        - donsadit@gmail.com
        - kyriox@gmail.com
        - mgraffg@gmail.com
        - sabinomiranda@gmail.com
        - dmocteo@gmail.com


    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: alway

env:
  global:
    - DISABLE_AMEND_COVERAGE_FROM_SRC=yes

# uncomment the following lines to override the default test script
# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'using Pkg; pkg"add https://github.com/sadit/TextSeach.jl"'

before_install:
  - julia -e 'using Pkg; pkg"add https://github.com/sadit/SimilaritySearch.jl https://github.com/sadit/KCenters.jl https://github.com/sadit/TextSearch.jl"'

after_success:
  - julia -e 'cd(Pkg.dir("TextClassification")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("TextClassification")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
